### ISSUE TITLE
Network buffer size warnings

### ISSUE THREAD

**Issue by davecromberge** [outlyerapp/dalmatinerdb#16]
The logs contain many instances of the following event:
`riak_core_sysmon_handler:handle_event:92 monitor busy_dist_port <0.12268.2>`

Riak will create this log entry whenever distributed erlang is overloaded. Since the error is being logged frequently, the buffer used for distributed erlang can be increased by adding +zdbbl KBytes in the vm.args.

For more info see here:
http://erlang.org/doc/man/erl.html#%2bzdbbl
https://github.com/basho/riak/blob/master/rel/files/vm.args#L40
http://www.snookles.com/slf-blog/2012/01/05/tcp-incast-what-is-it/

**Comment by davecromberge** [comment]
Additionally, calling `erlang:system_info(dist_buf_busy_limit)` on ddbn2 returns a current buffer limit of 1Mb.  According to the docs, the default limit is 1Mb, and a higher limit will give lower latency and higher throughput at the expense of higher memory usage.

**Comment by starstuck** [comment]
adding a line

```
erlang.distribution_buffer_size = 128MB
```

to /etc/ddb/ddb.conf seems to remove those warnings. Unfortunately it does not solve issues with timeouts.

**Comment by davecromberge** [comment]
One less warning to worry about :+1: 
Does @tomashley need to add the line above to chef?

**Comment by starstuck** [comment]
I had to bump it up to 256MB for current ring size. Closing issue.
