### ISSUE TITLE
Mmath nif is causing frontend to crash

### ISSUE THREAD

**Issue by starstuck** [outlyerapp/dalmatinerdb#40]
Process is killed with message in syslog
`[584632.374034] traps: 7_scheduler[10954] trap divide error ip:7f3c0770816e sp:7f3c309fcbf8 error:0 in aggr_nif.so[7f3c07705000+5000]`

**Comment by davecromberge** [comment]
@szarsti nice find - would this only pertain to floating point numbers?  

This could be unrelated, but, would it adversely affect the widgets on a dashboard? 

For example, some widgets sourced from riak have a fractional component to their datapoints. However the corresponding widget sourced from dalmatiner does not.
<img width="368" alt="screen shot 2016-04-06 at 11 26 23" src="https://cloud.githubusercontent.com/assets/164431/14313676/d023c384-fbea-11e5-8539-6b0357664429.png">
<img width="365" alt="screen shot 2016-04-06 at 11 28 04" src="https://cloud.githubusercontent.com/assets/164431/14313702/f7cccad4-fbea-11e5-8f1d-cebb35055d05.png">

<img width="359" alt="screen shot 2016-04-06 at 11 27 11" src="https://cloud.githubusercontent.com/assets/164431/14313701/f7c9d55e-fbea-11e5-9b26-4949c5e5e575.png">
<img width="355" alt="screen shot 2016-04-06 at 11 27 21" src="https://cloud.githubusercontent.com/assets/164431/14313677/d024a5d8-fbea-11e5-912c-8cb17b4c3be1.png">

**Comment by davecromberge** [comment]
Please disregard my previous comment, it appears to be as a result of interpolation as this does not occur on a lower resolution.

**Comment by starstuck** [comment]
Fixed in most recent mmath library.
